#=================================================================
# 对象存储配置
#=================================================================
storage:
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: __PLACEHOLDER_ACCESS_KEY__
    secretKey: __PLACEHOLDER_SECRET_KEY__
  aliyun-oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKey: __PLACEHOLDER_ACCESS_KEY__
    secretKey: __PLACEHOLDER_SECRET_KEY__
